name = "adurun-campaigns"
main = "functions/_worker.ts"
compatibility_date = "2024-06-01"

[durable_objects]
bindings = [{ name = "CAMPAIGN_DO", class_name = "CampaignDurableObject" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CampaignDurableObject"]

routes = [
  { pattern = "character-sheet-project.pages.dev/api/*", zone_name = "character-sheet-project.pages.dev" }
]
